### ISSUE TITLE
Need Guidance regarding contibuting

### ISSUE THREAD

**Issue by Baizkunthaz** [nrnb/gsoc2023_projects#1]
Hey, I am very willing and interested in contributing to the org, but as I am new to open source, could you please guide me on how to start?

**Comment by khanspers** [comment]
Hi @Baizkunthaz, this repo is simply an archive of our projects from last GSoC (2023). The main repo we use for listing projects of interest and for communication with potential mentors is https://github.com/nrnb/GoogleSummerOfCode/issues. However, in preparation for GSoC 2024, we will soon be closing all issues in that repo and mentors will then re-open relevant issues or post new projects. The list will be more accurate towards the end of January 2024. 

Feel free to take a look now, but beware that some of the projects listed may no longer be relevant.
